In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import re
sns.set(font_scale=1.5)

%config InlineBackend.figure_format = 'retina'
%matplotlib inline

In [3]:
df = pd.read_csv('/Users/dayosangowawa/Desktop/Side Projects 2022/EU congenital anomalies data analysis/final_df.csv')

In [4]:
df.describe()

,years,population,live_births,still_births,termination_of_pregnancy_for_fetal_anomaly_following_prenatal_diagnosis,total_no_of_cases,lb_proportion_,still_birth_proportion_,topfa_proportion_,gdp
count,34382.000000,34382.000000,34382.000000,34382.000000,34382.000000,34382.000000,34382.000000,34382.000000,34382.000000,3.438200e+04
mean,2008.531034,24871.431447,23.097784,0.631173,5.603135,29.332092,80.644124,2.494606,16.861287,1.398767e+12
std,4.803047,16594.349053,80.541063,2.318242,20.352230,97.639859,25.116032,7.308783,23.891891,1.127068e+12
min,2000.000000,2223.000000,1.000000,0.000000,0.000000,1.000000,1.470000,0.000000,0.000000,4.069516e+09
25%,2005.000000,10723.000000,2.000000,0.000000,0.000000,3.000000,66.670000,0.000000,0.000000,2.872265e+11
50%,2009.000000,21316.000000,5.000000,0.000000,1.000000,7.000000,92.860000,0.000000,1.070000,1.270712e+12
75%,2013.000000,33026.000000,15.000000,0.000000,3.000000,20.000000,100.000000,0.000000,27.500000,2.491110e+12
max,2016.000000,76439.000000,2487.000000,78.000000,422.000000,2685.000000,100.000000,83.330000,98.530000,3.883920e+12